# Text sensor for light intensity
# Depends on the light sensor from the misol_weather integration
text_sensor:
  - platform: template
    name: "${device_name} Light Intensity Text"
    id: ${device_id}_light_intensity_text
    icon: "mdi:weather-sunny"
    update_interval: 20s
    lambda: |-
      const float lux = id(${device_id}_light).state;
      if (isnan(lux)) {
        return { "Unknown" };
      } else if (lux < 1) {
        return { "Dark night" };
      } else if (lux < 10) {
        return { "Night" };
      } else if (lux < 100) {
        return { "Twilight" };
      } else if (lux < 1000) {
        return { "Very dark day" };
      } else if (lux < 10000) {
        return { "Overcast day" };
      } else if (lux < 25000) {
        return { "Daylight" };
      } else if (lux < 100000) {
        return { "Bright daylight" };
      } else {
        return { "Direct sunlight" };
      }
